val_of_blocks = {
        'operator_gt': {
            'color': '#59c059',
            'scratch_text': ' > ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' > ',
            'python_text2': '',
        },
        'operator_lt': {
            'color': '#59c059',
            'scratch_text': ' < ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' < ',
            'python_text2': '',
        },
        'operator_equals': {
            'color': '#59c059',
            'scratch_text': ' = ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' == ',
            'python_text2': '',
        },
        'operator_add': {
            'color': '#59c059',
            'scratch_text': ' + ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' + ',
            'python_text2': '',
        },
        'operator_subtract': {
            'color': '#59c059',
            'scratch_text': ' - ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' - ',
            'python_text2': '',
        },
        'operator_multiply': {
            'color': '#59c059',
            'scratch_text': ' * ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' * ',
            'python_text2': '',
        },
        'operator_divide': {
            'color': '#59c059',
            'scratch_text': ' / ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' / ',
            'python_text2': '',
        },
        'operator_and': {
            'color': '#59c059',
            'scratch_text': ' i ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' and ',
            'python_text2': '',
        },
        'operator_or': {
            'color': '#59c059',
            'scratch_text': ' lub ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': ' or ',
            'python_text2': '',
        },
        'operator_not': {
            'color': '#59c059',
            'scratch_text': 'nie ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'not ',
            'python_text2': '',
        },
        'operator_mod': {
            'color': '#59c059',
            'scratch_text': 'reszta z dzielenia ',
            'scratch_text2': ' przez ',
            'python_function': [],
            'python_text1': '',
            'python_text2': ' % ',
        },
        'operator_round': {
            'color': '#59c059',
            'scratch_text': 'zaokrąglij ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'round ',
            'python_text2': '',
        },
        'operator_length': {
            'color': '#59c059',
            'scratch_text': 'długość ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'len(',
            'python_text2': ')',
        },

        'operator_mathop': {
            'color': '#59c059',
            'scratch_text': '',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': '',
            'python_text2': '',
        },
        'operator_join': {
            'color': '#59c059',
            'scratch_text': 'połącz ',
            'scratch_text2': ' i ',
            'python_function': [],
            'python_text1': '',
            'python_text2': '.join(',
            'python_text3': ')',
        },
        'operator_letter_of': {
            'color': '#59c059',
            'scratch_text': 'litera ',
            'scratch_text2': ' z ',
            'python_function': [],
            'python_text1': '[',
            'python_text2': ']',
        },
        'operator_contains': {
            'color': '#59c059',
            'scratch_text': 'Czy ',
            'scratch_text2': ' zawiera ',
            'scratch_text3': ' ?',
            'python_function': [],
            'python_text1': '',
            'python_text2': ' in ',
        },

        'operator_random': {
            'color': '#59c059',
            'scratch_text': 'losuj liczbę od ',
            'scratch_text2': ' do ',
            'python_function': [],
            'python_text1': 'random(',
            'python_text2': ', ',
            'python_text3': ')',
        },

        'event_whenflagclicked': {
            'color': '#ffbf00',
            'scratch_text': 'Kiedy kliknięto ',
            'scratch_text2': '',
            'python_function': ['def if_clicked():', '# [Ciało funkcji - w tym wypadku powinno zwrócić "True" albo "False"]'],
            'python_text1': 'if is_clicked():',
            'python_text2': '',
        },
        'event_whenkeypressed': {
            'color': '#ffbf00',
            'scratch_text': 'Kiedy klawisz ',
            'scratch_text2': ' naciśnięty',
            'python_function': ['def if_key_pressed():', '# [Ciało funkcji - w tym wypadku powinno zwrócić "True" albo "False"]'],
            'python_text1': 'if if_key_pressed(',
            'python_text2': '):',
        },
        'event_whenthisspriteclicked': {
            'color': '#ffbf00',
            'scratch_text': 'Kiedy ten duszek kliknięty',
            'scratch_text2': '',
            'python_function': ['def if_sprite_pressed():', '# [Ciało funkcji - w tym wypadku powinno zwrócić "True" albo "False"]'],
            'python_text1': 'if if_sprite_pressed():',
            'python_text2': '',
        },

        'data_setvariableto': {
            'color': '#ff8c1a',
            'scratch_text': 'ustaw ',
            'scratch_text2': ' na ',
            'python_function': [],
            'python_text1': '',
            'python_text2': ' = ',
        },

        'control_repeat_until': {
            'color': '#ffab19',
            'scratch_text': 'powtarzaj aż ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'while ',
            'python_text2': '',
        },
        'control_wait': {
            'color': '#ffab19',
            'scratch_text': 'czekaj  ',
            'scratch_text2': ' sekund',
            'python_function': [],
            'python_text1': 'wait ',
            'python_text2': '',
        },
        'control_repeat': {
            'color': '#ffab19',
            'scratch_text': 'powtórz  ',
            'scratch_text2': ' razy',
            'python_function': [],
            'python_text1': 'for ',
            'python_text2': ' in range(',
            'python_text3': '):',
        },
        'control_forever': {
            'color': '#ffab19',
            'scratch_text': 'zawsze ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'while True:',
            'python_text2': '',
        },
        'control_if_else': {
            'color': '#ffab19',
            'scratch_text': 'jeżeli ',
            'scratch_text2': ' to',
            'scratch_text3': 'w przeciwnym razie',
            'python_function': [],
            'python_text1': 'if ',
            'python_text2': ':',
            'python_text3': 'else:',
        },
        'control_wait_until': {
            'color': '#ffab19',
            'scratch_text': 'czekaj aż ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'time.sleep(',
            'python_text2': ')',
        },
        'control_stop': {
            'color': '#ffab19',
            'scratch_text': 'zatrzymaj ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'break',
            'python_text2': '',
        },

        'motion_turnright': {
            'color': '#4c97ff',
            'scratch_text': 'obróć w prawo o ',
            'scratch_text2': '',
            'python_function': ['def turn_right(degree):', '# [Ciało funkcji służącej do obracania stworka]'],
            'python_text1': 'turn_right(',
            'python_text2': ')',
        },
        'motion_turnleft': {
            'color': '#4c97ff',
            'scratch_text': 'obróć w lewo o ',
            'scratch_text2': '',
            'python_function': ['def turn_left(degree):', '# [Ciało funkcji służącej do obracania stworka]'],
            'python_text1': 'turn_left(',
            'python_text2': ')',
        },
        'motion_movesteps': {
            'color': '#4c97ff',
            'scratch_text': 'przesuń o ',
            'scratch_text2': ' kroków',
            'python_function': ['def move_object(steps):', '# [Ciało funkcji służącej do obracania stworka]'],
            'python_text1': 'move_object(',
            'python_text2': ')',
        },

        'data_changevariableby': {
            'color': '#ff8c1a',
            'scratch_text': 'zmień ',
            'scratch_text2': ' na ',
            'python_function': [],
            'python_text1': '',
            'python_text2': ' = ',
        },
        'data_showvariable': {
            'color': '#ff8c1a',
            'scratch_text': 'pokaż zmienną ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'print(',
            'python_text2': ')',
        },
        'data_hidevariable': {
            'color': '#ff8c1a',
            'scratch_text': 'ukryj zmienną ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'hide(',
            'python_text2': ')',
        },
        'control_if': {
            'color': '#ffab19',
            'scratch_text': 'jeżeli ',
            'scratch_text2': ' to ',
            'python_function': [],
            'python_text1': 'if ',
            'python_text2': ':',
        },

        'looks_sayforsecs': {
            'color': '#9966ff',
            'scratch_text': 'Powiedz ',
            'scratch_text2': ' przez ',
            'scratch_text3': ' sekund',
            'python_function': [],
            'python_text1': 'print(???',# Todo do zastanowienia co może być za to
            'python_text2': ')',
        },
        'looks_say': {
            'color': '#9966ff',
            'scratch_text': 'Powiedz ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'print(say ',# Todo do zastanowienia co może być za to
            'python_text2': ')',
        },
        'looks_thinkforsecs': {
            'color': '#9966ff',
            'scratch_text': 'Pomyśl ',
            'scratch_text2': ' przez ',
            'scratch_text3': ' sekund',
            'python_function': [],
            'python_text1': 'Pomyśl przez',
            'python_text2': '',
        },
        'looks_think': { #Todo do zastanowienia co może być za to
            'color': '#9966ff',
            'scratch_text': 'Pomyśl ',
            'scratch_text2': '',
            'python_function': [],
            'python_text1': 'print(?? ',
            'python_text2': ')',
        },
    }