mathop_options = {
    'scratch_abs': 'wartość bezwzględna z ',
    'python_abs': 'abs',
    'scratch_floor': 'podłoga z ',
    'python_floor': 'floor',
    'scratch_ceiling': 'sufit z ',
    'python_ceiling': 'ceil',
    'scratch_sqrt': 'pierwiastek kwadratowy z',
    'python_sqrt': 'sqrt',
    'scratch_sin': 'sinus z ',
    'python_sin': 'math.sin',
    'scratch_cos': 'cosinus z ',
    'python_cos': 'math.cos',
    'scratch_tan': 'tangens z ',
    'python_tan': 'math.tan',
    'scratch_asin': 'arcus sinus z ',
    'python_asin': 'math.arsic',
    'scratch_acos': 'arcus cosinus z ',
    'python_acos': 'math.arcos',
    'python_atan': 'arcus tangens z ',
    'scratch_atan': 'math.arctan',
    'scratch_ln': 'logarytm naturalny z ',
    'python_ln': 'np.log',
    'scratch_log': 'log z ',
    'python_log': 'np.log',
    'scratch_e ^': 'e^ z ',
    'python_e ^': 'math.exp',
    'scratch_10 ^': '10^ z ',
    'python_10 ^': '10^',
}