type_of_logical_field = ['operator_gt', 'operator_lt']
type_of_variable_field = ['data_setvariableto', 'data_changevariableby']
type_of_loop_field = ['control_repeat_until', 'control_if']
type_of_motion_field = ['motion_turnright']
type_of_event_field = ['event_whenflagclicked']